from pathlib import Path

root = Path(__file__).parent / "dist"

head = """<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#151513"><title>{title} | Outlet Premium Lavras</title><meta name="description" content="{description}"><meta name="robots" content="{robots}"><link rel="canonical" href="https://outlet-premium-lavras.duducraft11.chatgpt.site/{route}"><link rel="icon" href="/images/logo-premium.svg" type="image/svg+xml"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"><link rel="stylesheet" href="/v3.css"><script defer src="/v3.js"></script></head><body data-page="{page}"><a class="skip" href="#main">Ir para o conteúdo</a><div class="topbar">OUTLET PREMIUM LAVRAS <span>MODA MASCULINA · CENTRO DE LAVRAS</span></div><header class="header"><a class="logo" href="/" aria-label="Outlet Premium Lavras, página inicial"><img src="/images/logo-premium.svg" alt="Outlet Premium" width="64" height="64"></a><nav class="nav" aria-label="Principal"><a href="/" data-nav="home">Início</a><a href="/catalogo/" data-nav="catalog">Catálogo</a><a href="/#loja" data-nav="store">A loja</a></nav><div class="header-end"><a href="/checkout/" class="bag-link" aria-label="Sacola e checkout">Sacola <span id="cart-count">0</span></a><button class="menu-toggle" id="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Abrir menu"><span></span><span></span></button></div></header><nav id="mobile-nav" class="mobile-nav" aria-label="Menu móvel" hidden><a href="/">Início</a><a href="/catalogo/">Catálogo</a><a href="/checkout/">Sacola</a><a href="/#loja">A loja</a></nav><main id="main">"""

foot = """</main><footer class="footer"><div class="footer-inner"><div><img src="/images/logo-premium.svg" alt="Outlet Premium" width="74" height="74"><p>Multimarcas para o dia a dia.<br>Lavras, Minas Gerais.</p></div><div><strong>Explore</strong><a href="/catalogo/">Catálogo</a><a href="/checkout/">Sacola e checkout</a><a href="/admin/">Área administrativa</a></div><div><strong>Contato</strong><a href="https://wa.me/5535997687127">WhatsApp</a><a href="https://www.instagram.com/outlet.premium.lavras/">Instagram</a><a href="tel:+553530134842">(35) 3013-4842</a></div><div><strong>Encontre a loja</strong><p>Rua Doutor Álvaro Botelho, 188<br>Centro · Lavras, MG</p><a href="https://www.google.com/maps/search/?api=1&query=Rua+Doutor+Alvaro+Botelho+188+Lavras+MG">Abrir mapa</a></div></div><div class="footer-bottom">© 2026 Outlet Premium Lavras <span>Fotos de referência. Disponibilidade e valores sob confirmação da loja.</span></div></footer></body></html>"""

def save(route, title, description, page, body):
    directory = root / route
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "index.html").write_text(head.format(title=title, description=description, page=page, route=(route + "/" if route else ""), robots=("noindex, nofollow" if page in ("checkout", "admin") else "index, follow")) + body + foot, encoding="utf-8")

save("", "Moda masculina multimarcas", "Moda masculina multimarcas no Centro de Lavras, MG.", "home", """
<section class="hero" aria-label="Outlet Premium Lavras"><img src="/images/camisa-xadrez.png" alt="Modelo usando camisa xadrez e jeans da seleção masculina" fetchpriority="high"><div class="hero-wash"></div><div class="hero-signature"><span>OUTLET PREMIUM</span><span>LAVRAS · MG</span></div></section>
<section class="intro block"><div class="eyebrow">O QUE NOS MOVE</div><div><h1>Estilo que acompanha a sua rotina.</h1><p>Uma curadoria multimarcas para vestir bem em qualquer ocasião. Conheça as peças, descubra combinações e encontre a sua próxima escolha.</p><a class="text-link" href="/catalogo/">Conhecer o catálogo</a></div></section>
<section class="home-gallery block"><div class="section-header"><div><span class="eyebrow">EM DESTAQUE</span><h2>Peças para descobrir.</h2></div><a class="text-link" href="/catalogo/">Ver catálogo completo</a></div><div class="gallery-grid"><a href="/catalogo/#camisetas-neutras"><img src="/images/camisetas-neutras.png" alt="Camisetas em cores neutras"><span>Camisetas</span></a><a href="/catalogo/#camisa-xadrez"><img src="/images/camisa-xadrez.png" alt="Modelo com camisa xadrez"><span>Camisas</span></a><a href="/catalogo/#jeans-escuro"><div class="screenshot-crop crop-jeans-dark"><img src="/images/instagram-produtos.png" alt="Jeans escuro"></div><span>Jeans</span></a></div></section>
<section class="story"><div class="story-copy"><span class="eyebrow">A SELEÇÃO</span><h2>Essenciais com personalidade.</h2><p>Camisetas de diversas cores, denim, camisas e acessórios para construir seu estilo. Veja o catálogo e converse com a equipe sobre tamanhos e disponibilidade.</p><a class="text-link" href="/catalogo/">Ver as peças</a></div><img src="/images/camisetas-neutras.png" alt="Camisetas masculinas em tons neutros"></section>
<section class="store block" id="loja"><span class="eyebrow">VENHA CONHECER</span><div class="store-grid"><div><h2>De perto, fica ainda melhor.</h2><p>Rua Doutor Álvaro Botelho, 188<br>Centro · Lavras, MG · 37200-000</p></div><div class="store-links"><a href="https://www.google.com/maps/search/?api=1&query=Rua+Doutor+Alvaro+Botelho+188+Lavras+MG">Como chegar</a><a href="https://wa.me/5535997687127">Falar no WhatsApp</a><a href="https://www.instagram.com/outlet.premium.lavras/">Acompanhar no Instagram</a></div></div></section>
""")

save("catalogo", "Catálogo", "Explore camisetas, jeans, camisas e acessórios da Outlet Premium Lavras.", "catalog", """
<section class="catalog-intro block"><span class="eyebrow">OUTLET PREMIUM / LAVRAS</span><h1>O catálogo.</h1><p>Peças e inspirações para você encontrar o que combina com seu estilo. Valores, tamanhos e disponibilidade são confirmados diretamente com a loja.</p></section>
<section class="catalog-area block"><div class="catalog-tools"><div class="filters" role="group" aria-label="Filtrar por categoria"><button type="button" class="filter active" data-filter="todos" aria-pressed="true">Todos</button><button type="button" class="filter" data-filter="camisetas">Camisetas</button><button type="button" class="filter" data-filter="calcas">Calças</button><button type="button" class="filter" data-filter="camisas">Camisas</button><button type="button" class="filter" data-filter="jaquetas">Jaquetas</button><button type="button" class="filter" data-filter="acessorios">Acessórios</button></div><label class="search"><span class="visually-hidden">Buscar peças</span><input id="catalog-search" type="search" placeholder="Buscar uma peça"></label></div><p class="catalog-count" id="catalog-count" aria-live="polite"></p><div class="product-grid" id="product-grid"></div><div id="empty-state" class="empty" hidden>Nenhuma peça encontrada. Experimente outro termo.</div><p class="catalog-disclaimer">As fotos da loja são referências da seleção divulgada. Imagens de camisas sociais, cintos e polos são ilustrativas. Nenhuma peça, valor ou estoque é garantido pelo site.</p></section>
<dialog id="product-dialog" class="product-dialog"><button type="button" class="dialog-close" aria-label="Fechar">×</button><div class="dialog-layout"><div id="dialog-media" class="dialog-media"></div><div class="dialog-copy"><span id="dialog-category" class="eyebrow"></span><h2 id="dialog-title"></h2><p id="dialog-description"></p><div id="dialog-facts" class="facts"></div><p class="soft-note">Preço e tamanhos sob consulta.</p><div class="dialog-actions"><button type="button" id="add-to-cart" class="button">Adicionar à sacola</button><a id="dialog-whatsapp" class="text-link" href="https://wa.me/5535997687127">Consultar no WhatsApp</a></div></div></div></dialog>
""")

save("checkout", "Sacola e checkout", "Monte sua sacola e simule uma solicitação de compra.", "checkout", """
<section class="simple-intro block"><span class="eyebrow">SACOLA</span><h1>Seu pedido.</h1><p>Confira suas escolhas e informe como prefere receber. Este checkout é uma demonstração: preços e disponibilidade precisam ser confirmados pela loja antes de qualquer pagamento.</p></section>
<section class="checkout-layout block"><div><div id="cart-items" class="cart-items"></div><div id="cart-empty" class="empty" hidden>Sua sacola está vazia. <a href="/catalogo/">Veja o catálogo.</a></div><form id="checkout-form" class="checkout-form"><h2>Seus dados</h2><div class="field-grid"><label>Nome completo<input name="name" autocomplete="name" required></label><label>Telefone / WhatsApp<input name="phone" inputmode="tel" autocomplete="tel" required></label><label>E-mail<input name="email" type="email" autocomplete="email" required></label></div><h2>Recebimento</h2><div class="choice-row"><label><input type="radio" name="fulfillment" value="pickup" checked> Retirada na loja</label><label><input type="radio" name="fulfillment" value="delivery"> Entrega</label></div><div id="delivery-fields" hidden><div class="field-grid"><label>CEP<input name="zip" id="zip" inputmode="numeric" maxlength="9" autocomplete="postal-code"></label><label>Rua<input name="street" autocomplete="street-address"></label><label>Número<input name="number" inputmode="numeric"></label><label>Complemento<input name="extra"></label><label>Bairro<input name="district"></label><label>Cidade<input name="city" value="Lavras"></label></div><button class="secondary-button" id="calculate-shipping" type="button">Calcular taxa estimada</button><p id="shipping-result" class="soft-note" aria-live="polite">Informe o CEP para uma estimativa demonstrativa.</p></div><h2>Preferência de pagamento</h2><div class="choice-row payments"><label><input type="radio" name="payment" value="Pix" checked> Pix</label><label><input type="radio" name="payment" value="Débito"> Cartão de débito</label><label><input type="radio" name="payment" value="Crédito"> Cartão de crédito</label></div><label class="full-label">Observações<textarea name="notes" rows="3" placeholder="Tamanho, cor ou outra informação útil"></textarea></label><p class="soft-note">Não informe número de cartão ou dados sensíveis. Nenhum pagamento será processado aqui.</p><button class="button" type="submit">Criar pedido de demonstração</button><p id="checkout-message" class="form-message" role="status"></p></form></div><aside class="summary"><span class="eyebrow">RESUMO</span><h2>Sua sacola</h2><div id="summary-items"></div><div class="summary-line"><span>Produtos</span><strong>Sob consulta</strong></div><div class="summary-line"><span>Entrega</span><strong id="summary-shipping">Retirada grátis</strong></div><p>Preços e taxa final dependem de confirmação da loja.</p><a href="/catalogo/" class="text-link">Continuar vendo peças</a></aside></section>
""")

save("admin", "Painel de demonstração", "Painel público de demonstração dos pedidos neste navegador.", "admin", """
<section class="simple-intro block"><span class="eyebrow">ÁREA ADMINISTRATIVA · DEMONSTRAÇÃO</span><h1>Pedidos.</h1><p>Este painel público demonstra o gerenciamento de pedidos criados neste navegador. A senha abaixo é fictícia e não protege dados reais.</p></section><section class="admin-layout block"><div class="admin-login" id="admin-login"><h2>Acessar demonstração</h2><p>Senha fictícia já preenchida para você testar o painel.</p><form id="admin-form"><label>Senha de demonstração<input id="admin-password" type="text" value="outlet-demo-2026" autocomplete="off"></label><button class="button" type="submit">Abrir painel</button></form><p id="admin-error" class="form-message" role="status"></p></div><div id="admin-panel" hidden><div class="admin-heading"><div><h2>Gerenciar pedidos</h2><p>Exemplos e pedidos de teste salvos apenas neste dispositivo.</p></div><button class="secondary-button" id="reset-demo" type="button">Restaurar exemplos</button></div><div class="admin-stats"><div><span>Pedidos</span><strong id="stat-total">0</strong></div><div><span>Novos</span><strong id="stat-new">0</strong></div><div><span>Finalizados</span><strong id="stat-done">0</strong></div></div><div class="admin-toolbar"><label class="search"><span class="visually-hidden">Buscar pedidos</span><input id="order-search" type="search" placeholder="Buscar por número ou nome"></label><select id="order-filter" aria-label="Filtrar por status"><option value="todos">Todos os status</option><option value="Novo">Novo</option><option value="Em atendimento">Em atendimento</option><option value="Finalizado">Finalizado</option><option value="Cancelado">Cancelado</option></select></div><div id="order-list" class="order-list"></div><p class="soft-note">As alterações ficam somente neste navegador. Para receber pedidos reais e gerenciá-los em vários dispositivos, será necessária uma integração segura com servidor e autenticação verdadeira.</p></div></section>
""")
